apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-feed
  name: backend-feed-d
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - image: kelvinbush/udagram-api-feed:v1
          name: backend-feed
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "2048Mi"
              cpu: "2000m"
          env:
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: udagram-configmap
                  key: URL
            - name: AWS_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: udagram-configmap
                  key: AWS_BUCKET
            - name: AWS_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: udagram-configmap
                  key: AWS_PROFILE
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: udagram-configmap
                  key: AWS_REGION
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: udagram-secret
                  key: JWT_SECRET
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: udagram-configmap
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: udagram-configmap
                  key: POSTGRES_HOST
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: udagram-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: udagram-secret
                  key: POSTGRES_USERNAME
          volumeMounts:
            - name: aws-secret
              mountPath: "/root/.aws/"
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret
